# Generated by Django 3.1.3 on 2021-01-22 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato')], max_length=1)),
                ('castrado', models.CharField(choices=[('P', 'Não sei informar'), ('S', 'Sim'), ('N', 'Não')], default='P', max_length=1)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('vacinado', models.CharField(choices=[('P', 'Não sei informar'), ('S', 'Sim'), ('N', 'Não'), ('I', 'Incompleto')], default='P', max_length=1)),
                ('temperamento', models.CharField(choices=[('D', 'Dócil'), ('A', 'Ativo'), ('B', 'Brabo')], default='D', max_length=1)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pet_lost',
            },
        ),
    ]
